const flashcards = [
    { id: 1, front: <h1>abuse</h1>, back: <p>학대하다</p> },
    { id: 2, front: <h1>accommodate</h1>, back: <p>숙박할 곳을 제공하다, 수용하다</p> },
    { id: 3, front: <h1>accompany</h1>, back: <p>동반하다</p> },
    { id: 4, front: <h1>accomplish</h1>, back: <p>성취하다</p> },
    { id: 5, front: <h1>accord</h1>, back: <p>일치, 허용하다</p> },
    { id: 6, front: <h1>accurate</h1>, back: <p>정확한, 정밀한</p> },
    { id: 7, front: <h1>acknowledge</h1>, back: <p>인정하다</p> },
    { id: 8, front: <h1>acrophobia</h1>, back: <p>고소공포증</p> },
    { id: 9, front: <h1>acute</h1>, back: <p>극심한, 급성의</p> },
    { id: 10, front: <h1>adequate</h1>, back: <p>충분한</p> },
    { id: 11, front: <h1>adhesive</h1>, back: <p>접착제, 잘 들러붙는</p> },
    { id: 12, front: <h1>adjacent</h1>, back: <p>인접한</p> },
    { id: 13, front: <h1>admonish</h1>, back: <p>훈계하다, 꾸짖다</p> },
    { id: 14, front: <h1>adopt</h1>, back: <p>채택하다</p> },
    { id: 15, front: <h1>adore</h1>, back: <p>아주 좋아하다, 숭배하다</p> },
    { id: 16, front: <h1>advent</h1>, back: <p>출현, 도래</p> },
    { id: 17, front: <h1>adverse</h1>, back: <p>불리한</p> },
    { id: 18, front: <h1>affection</h1>, back: <p>애정</p> },
    { id: 19, front: <h1>afflict</h1>, back: <p>괴롭히다</p> },
    { id: 20, front: <h1>affluent</h1>, back: <p>부유한, 풍족한</p> },
    { id: 21, front: <h1>aggression</h1>, back: <p>공격</p> },
    { id: 22, front: <h1>agitate</h1>, back: <p>뒤흔들다, 선동하다</p> },
    { id: 23, front: <h1>agriculture</h1>, back: <p>농업</p> },
    { id: 24, front: <h1>ailment</h1>, back: <p>질병</p> },
    { id: 25, front: <h1>airsick</h1>, back: <p>비행기 멀미를 하는</p> },
    { id: 26, front: <h1>aisle</h1>, back: <p>통로</p> },
    { id: 27, front: <h1>alien</h1>, back: <p>외국의, 외계인</p> },
    { id: 28, front: <h1>alleviate</h1>, back: <p>완화하다, 경감하다</p> },
    { id: 29, front: <h1>altar</h1>, back: <p>제단</p> },
    { id: 30, front: <h1>alter</h1>, back: <p>변경하다</p> },
    { id: 31, front: <h1>anecdote</h1>, back: <p>일화</p> },
    { id: 32, front: <h1>anesthesia</h1>, back: <p>마취</p> },
    { id: 33, front: <h1>annihilate</h1>, back: <p>전멸시키다</p> },
    { id: 34, front: <h1>antipathy</h1>, back: <p>반감</p> },
    { id: 35, front: <h1>anxiety</h1>, back: <p>불안</p> },
    { id: 36, front: <h1>apparatus</h1>, back: <p>장치</p> },
    { id: 37, front: <h1>applause</h1>, back: <p>박수</p> },
    { id: 38, front: <h1>appreciate</h1>, back: <p>감사하다, 진가를 인정하다</p> },
    { id: 39, front: <h1>apprehend</h1>, back: <p>체포하다</p> },
    { id: 40, front: <h1>appropriate</h1>, back: <p>적절한, 도용하다</p> },
    { id: 41, front: <h1>approve</h1>, back: <p>승인하다</p> },
    { id: 42, front: <h1>aquarium</h1>, back: <p>수족관</p> },
    { id: 43, front: <h1>archaeology</h1>, back: <p>고고학</p> },
    { id: 44, front: <h1>arise</h1>, back: <p>발생하다</p> },
    { id: 45, front: <h1>arithmetic</h1>, back: <p>산수, 산술</p> },
    { id: 46, front: <h1>artery</h1>, back: <p>동맥</p> },
    { id: 47, front: <h1>aspect</h1>, back: <p>측면</p> },
    { id: 48, front: <h1>aspire</h1>, back: <p>열망하다</p> },
    { id: 49, front: <h1>assassinate</h1>, back: <p>암살하다</p> },
    { id: 50, front: <h1>assault</h1>, back: <p>공격하다</p> },
    { id: 51, front: <h1>assemble</h1>, back: <p>모이다, 조립하다</p> },
    { id: 52, front: <h1>assert</h1>, back: <p>주장하다</p> },
    { id: 53, front: <h1>astonish</h1>, back: <p>놀라게 하다</p> },
    { id: 54, front: <h1>astrology</h1>, back: <p>점성술</p> },
    { id: 55, front: <h1>athlete</h1>, back: <p>운동선수</p> },
    { id: 56, front: <h1>attach</h1>, back: <p>붙이다</p> },
    { id: 57, front: <h1>attribute</h1>, back: <p>속성, ~가 원인이다</p> },
    { id: 58, front: <h1>authentic</h1>, back: <p>진정한</p> },
    { id: 59, front: <h1>avalanche</h1>, back: <p>눈사태</p> },
    { id: 60, front: <h1>axis</h1>, back: <p>축, 중심축</p> },
    { id: 61, front: <h1>bachelor</h1>, back: <p>미혼남자, 학사</p> },
    { id: 62, front: <h1>banish</h1>, back: <p>추방하다</p> },
    { id: 63, front: <h1>bankrupt</h1>, back: <p>파산한</p> },
    { id: 64, front: <h1>banner</h1>, back: <p>현수막</p> },
    { id: 65, front: <h1>barter</h1>, back: <p>물물교환하다</p> },
    { id: 66, front: <h1>biography</h1>, back: <p>전기</p> },
    { id: 67, front: <h1>biology</h1>, back: <p>생물학</p> },
    { id: 68, front: <h1>bleak</h1>, back: <p>음침한, 황량한</p> },
    { id: 69, front: <h1>bother</h1>, back: <p>곤란하게 하다</p> },
    { id: 70, front: <h1>breakthrough</h1>, back: <p>돌파구, 중요한 발전</p> },
    { id: 71, front: <h1>brilliant</h1>, back: <p>뛰어난, 훌륭한</p> },
    { id: 72, front: <h1>brink</h1>, back: <p>경계, 가장자리</p> },
    { id: 73, front: <h1>brisk</h1>, back: <p>활기 있는, 기운찬</p> },
    { id: 74, front: <h1>brook</h1>, back: <p>개울, 시내</p> },
    { id: 75, front: <h1>bunch</h1>, back: <p>다발, 송이</p> },
    { id: 76, front: <h1>burden</h1>, back: <p>부담, 짐</p> },
    { id: 77, front: <h1>cancer</h1>, back: <p>암</p> },
    { id: 78, front: <h1>candidate</h1>, back: <p>후보자</p> },
    { id: 79, front: <h1>capture</h1>, back: <p>붙잡다, 포획하다</p> },
    { id: 80, front: <h1>catalyst</h1>, back: <p>촉매제</p> },
    { id: 81, front: <h1>cattle</h1>, back: <p>소, 가축</p> },
    { id: 82, front: <h1>cavity</h1>, back: <p>구멍, 충치</p> },
    { id: 83, front: <h1>cease</h1>, back: <p>중단하다, 그만두다</p> },
    { id: 84, front: <h1>celebrity</h1>, back: <p>유명인사</p> },
    { id: 85, front: <h1>cemetery</h1>, back: <p>묘지</p> },
    { id: 86, front: <h1>chemical</h1>, back: <p>화학의, 화학물질</p> },
    { id: 87, front: <h1>choke</h1>, back: <p>숨이 막히다, 목을 조르다</p> },
    { id: 88, front: <h1>chuckle</h1>, back: <p>킬킬 웃다</p> },
    { id: 89, front: <h1>churn</h1>, back: <p>휘젓다, 혼동시키다</p> },
    { id: 90, front: <h1>clown</h1>, back: <p>광대</p> },
    { id: 91, front: <h1>cluster</h1>, back: <p>무리, 집합체</p> },
    { id: 92, front: <h1>cognitive</h1>, back: <p>인식의, 인지의</p> },
    { id: 93, front: <h1>collapse</h1>, back: <p>붕괴하다, 무너지다</p> },
    { id: 94, front: <h1>colleague</h1>, back: <p>동료</p> },
    { id: 95, front: <h1>combat</h1>, back: <p>전투, 싸움</p> },
    { id: 96, front: <h1>commodity</h1>, back: <p>상품, 물품</p> },
    { id: 97, front: <h1>compassion</h1>, back: <p>동정, 연민</p> },
    { id: 98, front: <h1>complement</h1>, back: <p>보충물, 보완하다</p> },
    { id: 99, front: <h1>compliment</h1>, back: <p>칭찬, 찬사</p> },
    { id: 100, front: <h1>compose</h1>, back: <p>구성하다, 작곡하다</p> },
    { id: 101, front: <h1>conceal</h1>, back: <p>숨기다, 감추다</p> },
    { id: 102, front: <h1>concede</h1>, back: <p>인정하다, 양보하다</p> },
    { id: 103, front: <h1>conceive</h1>, back: <p>상상하다, 생각하다</p> },
    { id: 104, front: <h1>concentrate</h1>, back: <p>집중하다</p> },
    { id: 105, front: <h1>conclude</h1>, back: <p>결론을 내리다, 끝내다</p> },
    { id: 106, front: <h1>condense</h1>, back: <p>압축하다, 요약하다</p> },
    { id: 107, front: <h1>conduct</h1>, back: <p>수행하다, 지휘하다</p> },
    { id: 108, front: <h1>confess</h1>, back: <p>고백하다</p> },
    { id: 109, front: <h1>conflict</h1>, back: <p>갈등, 충돌하다</p> },
    { id: 110, front: <h1>conform</h1>, back: <p>따르다, 순응하다</p> },
    { id: 111, front: <h1>conscience</h1>, back: <p>양심</p> },
    { id: 112, front: <h1>conserve</h1>, back: <p>보존하다</p> },
    { id: 113, front: <h1>console</h1>, back: <p>위로하다</p> },
    { id: 114, front: <h1>conspicuous</h1>, back: <p>눈에 띄는</p> },
    { id: 115, front: <h1>conspire</h1>, back: <p>음모를 꾸미다, 공모하다</p> },
    { id: 116, front: <h1>consternation</h1>, back: <p>큰 실망, 경악</p> },
    { id: 117, front: <h1>constitute</h1>, back: <p>구성하다, 형성하다</p> },
    { id: 118, front: <h1>contempt</h1>, back: <p>경멸, 멸시</p> },
    { id: 119, front: <h1>contrast</h1>, back: <p>대조, 대조를 이루다</p> },
    { id: 120, front: <h1>controvert</h1>, back: <p>논쟁하다, 반박하다</p> },
    { id: 121, front: <h1>convene</h1>, back: <p>소집하다, 모이다</p> },
    { id: 122, front: <h1>convenience</h1>, back: <p>편의, 편리함</p> },
    { id: 123, front: <h1>converse</h1>, back: <p>대화하다, 정반대</p> },
    { id: 124, front: <h1>convince</h1>, back: <p>확신시키다, 납득시키다</p> },
    { id: 125, front: <h1>cooperate</h1>, back: <p>협력하다</p> },
    { id: 126, front: <h1>correspond</h1>, back: <p>일치하다, 서신을 교환하다</p> },
    { id: 127, front: <h1>corridor</h1>, back: <p>복도</p> },
    { id: 128, front: <h1>corrupt</h1>, back: <p>부패한, 타락한</p> },
    { id: 129, front: <h1>cramp</h1>, back: <p>경련, 쥐</p> },
    { id: 130, front: <h1>crawl</h1>, back: <p>기어가다</p> },
    { id: 131, front: <h1>creed</h1>, back: <p>신조, 교리</p> },
    { id: 132, front: <h1>creep</h1>, back: <p>기어가다, 몰래 들어가다</p> },
    { id: 133, front: <h1>crude</h1>, back: <p>천연 그대로의, 원시의</p> },
    { id: 134, front: <h1>culprit</h1>, back: <p>범인, 범죄자</p> },
    { id: 135, front: <h1>dagger</h1>, back: <p>단검, 짧은 칼</p> },
    { id: 136, front: <h1>debate</h1>, back: <p>토론, 논쟁하다</p> },
    { id: 137, front: <h1>declare</h1>, back: <p>선언하다, 공표하다</p> },
    { id: 138, front: <h1>decline</h1>, back: <p>쇠퇴하다, 거절하다</p> },
    { id: 139, front: <h1>deduce</h1>, back: <p>추론하다</p> },
    { id: 140, front: <h1>deflect</h1>, back: <p>빗나가게 하다, 방향을 바꾸다</p> },
    { id: 141, front: <h1>delicate</h1>, back: <p>섬세한, 민감한</p> },
    { id: 142, front: <h1>depict</h1>, back: <p>묘사하다, 그리다</p> },
    { id: 143, front: <h1>deplete</h1>, back: <p>고갈시키다, 다 써버리다</p> },
    { id: 144, front: <h1>deposit</h1>, back: <p>예금, 예치하다</p> },
    { id: 145, front: <h1>deprive</h1>, back: <p>박탈하다, 빼앗다</p> },
    { id: 146, front: <h1>derive</h1>, back: <p>유래하다, 얻다</p> },
    { id: 147, front: <h1>dermatologist</h1>, back: <p>피부과 의사</p> },
    { id: 148, front: <h1>descend</h1>, back: <p>내려가다, 하강하다</p> },
    { id: 149, front: <h1>deteriorate</h1>, back: <p>악화되다, 나빠지다</p> },
    { id: 150, front: <h1>dilute</h1>, back: <p>희석하다, 묽게 하다</p> },
    { id: 151, front: <h1>discern</h1>, back: <p>알아보다, 구별하다</p> },
    { id: 152, front: <h1>disciple</h1>, back: <p>제자, 사도</p> },
    { id: 153, front: <h1>discipline</h1>, back: <p>훈육, 규율</p> },
    { id: 154, front: <h1>disguise</h1>, back: <p>위장하다, 변장</p> },
    { id: 155, front: <h1>dismiss</h1>, back: <p>무시하다, 해고하다</p> },
    { id: 156, front: <h1>disposition</h1>, back: <p>성격, 기질</p> },
    { id: 157, front: <h1>dispute</h1>, back: <p>논쟁, 분쟁</p> },
    { id: 158, front: <h1>dissertation</h1>, back: <p>논문, 학위 논문</p> },
    { id: 159, front: <h1>distinguish</h1>, back: <p>구별하다</p> },
    { id: 160, front: <h1>diverse</h1>, back: <p>다양한, 여러 가지의</p> },
    { id: 161, front: <h1>dreary</h1>, back: <p>우울한, 쓸쓸한</p> },
    { id: 162, front: <h1>drown</h1>, back: <p>물에 빠져 죽다</p> },
    { id: 163, front: <h1>dubious</h1>, back: <p>의심스러운, 불확실한</p> },
    { id: 164, front: <h1>dwell</h1>, back: <p>거주하다, 생각에 잠기다</p> },
    { id: 165, front: <h1>dwindle</h1>, back: <p>점점 줄다, 약해지다</p> },
    { id: 166, front: <h1>eccentric</h1>, back: <p>별난, 괴짜의</p> },
    { id: 167, front: <h1>efficient</h1>, back: <p>효율적인</p> },
    { id: 168, front: <h1>elaborate</h1>, back: <p>정교한, 상세한</p> },
    { id: 169, front: <h1>embargo</h1>, back: <p>통상 중지, 무역 금지</p> },
    { id: 170, front: <h1>emergency</h1>, back: <p>비상사태, 긴급 상황</p> },
    { id: 171, front: <h1>encounter</h1>, back: <p>맞닥뜨리다, 부딪히다</p> },
    { id: 172, front: <h1>enhance</h1>, back: <p>향상시키다, 강화하다</p> },
    { id: 173, front: <h1>entangle</h1>, back: <p>얽히게 하다, 뒤얽히다</p> },
    { id: 174, front: <h1>enthusiastic</h1>, back: <p>열정적인</p> },
    { id: 175, front: <h1>equate</h1>, back: <p>동등하게 다루다, 동일시하다</p> },
    { id: 176, front: <h1>eradicate</h1>, back: <p>근절하다, 박멸하다</p> },
    { id: 177, front: <h1>eradication</h1>, back: <p>근절, 박멸</p> },
    { id: 178, front: <h1>estate</h1>, back: <p>재산, 부동산</p> },
    { id: 179, front: <h1>esteem</h1>, back: <p>존경, 존경하다</p> },
    { id: 180, front: <h1>ethics</h1>, back: <p>윤리, 도덕</p> },
    { id: 181, front: <h1>ethnic</h1>, back: <p>민족의, 인종의</p> },
    { id: 182, front: <h1>eulogy</h1>, back: <p>추도사, 찬사</p> },
    { id: 183, front: <h1>evacuate</h1>, back: <p>대피하다, 철수하다</p> },
    { id: 184, front: <h1>evade</h1>, back: <p>피하다, 회피하다</p> },
    { id: 185, front: <h1>excavate</h1>, back: <p>발굴하다</p> },
    { id: 186, front: <h1>exceed</h1>, back: <p>초과하다, 뛰어넘다</p> },
    { id: 187, front: <h1>exclusive</h1>, back: <p>배타적인, 전용의</p> },
    { id: 188, front: <h1>executive</h1>, back: <p>경영진, 임원</p> },
    { id: 189, front: <h1>exhibit</h1>, back: <p>전시하다, 나타내다</p> },
    { id: 190, front: <h1>expire</h1>, back: <p>만료되다, 기한이 지나다</p> },
    { id: 191, front: <h1>explore</h1>, back: <p>탐험하다, 조사하다</p> },
    { id: 192, front: <h1>extend</h1>, back: <p>확장하다, 연장하다</p> },
    { id: 193, front: <h1>extinct</h1>, back: <p>멸종된, 사라진</p> },
    { id: 194, front: <h1>extravagance</h1>, back: <p>낭비, 사치</p> },
    { id: 195, front: <h1>faint</h1>, back: <p>희미한, 기절하다</p> },
    { id: 196, front: <h1>feasible</h1>, back: <p>실행 가능한, 가능성 있는</p> },
    { id: 197, front: <h1>fertile</h1>, back: <p>비옥한, 다산의</p> },
    { id: 198, front: <h1>fierce</h1>, back: <p>사나운, 격렬한</p> },
    { id: 199, front: <h1>flatter</h1>, back: <p>아첨하다, 추켜세우다</p> },
    { id: 200, front: <h1>fluctuation</h1>, back: <p>변동, 오르내림</p> },
    { id: 201, front: <h1>forbid</h1>, back: <p>금지하다, 막다</p> },
    { id: 202, front: <h1>former</h1>, back: <p>전자의, 이전의</p> },
    { id: 203, front: <h1>fragile</h1>, back: <p>깨지기 쉬운, 연약한</p> },
    { id: 204, front: <h1>fraud</h1>, back: <p>사기, 사기꾼</p> },
    { id: 205, front: <h1>frequent</h1>, back: <p>빈번한, 자주 일어나는</p> },
    { id: 206, front: <h1>frigid</h1>, back: <p>몹시 추운, 냉랭한</p> },
    { id: 207, front: <h1>frustrate</h1>, back: <p>좌절시키다,방해하다</p> },
    { id: 208, front: <h1>fundamental</h1>, back: <p>근본적인, 기본적인</p> },
    { id: 209, front: <h1>furthermore</h1>, back: <p>게다가, 더욱이</p> },
    { id: 210, front: <h1>futile</h1>, back: <p>헛된, 소용없는</p> },
    { id: 211, front: <h1>gallery</h1>, back: <p>화랑, 전시실</p> },
    { id: 212, front: <h1>generous</h1>, back: <p>관대한, 너그러운</p> },
    { id: 213, front: <h1>geography</h1>, back: <p>지리학</p> },
    { id: 214, front: <h1>geometry</h1>, back: <p>기하학</p> },
    { id: 215, front: <h1>gigantic</h1>, back: <p>거대한, 엄청난</p> },
    { id: 216, front: <h1>grant</h1>, back: <p>승인하다, 보조금</p> },
    { id: 217, front: <h1>grasp</h1>, back: <p>꽉 붙잡다, 이해하다</p> },
    { id: 218, front: <h1>gravity</h1>, back: <p>중력, 심각성</p> },
    { id: 219, front: <h1>growl</h1>, back: <p>으르릉거리다, 낮게 울다</p> },
    { id: 220, front: <h1>harass</h1>, back: <p>괴롭히다</p> },
    { id: 221, front: <h1>harsh</h1>, back: <p>가혹한, 엄한</p> },
    { id: 222, front: <h1>herbivore</h1>, back: <p>초식 동물</p> },
    { id: 223, front: <h1>hierarchy</h1>, back: <p>계급, 계급제도</p> },
    { id: 224, front: <h1>hilarious</h1>, back: <p>아주 웃기는</p> },
    { id: 225, front: <h1>household</h1>, back: <p>가정의, 가정</p> },
    { id: 226, front: <h1>humble</h1>, back: <p>겸손한, 낮은</p> },
    { id: 227, front: <h1>humid</h1>, back: <p>습한, 습도가 높은</p> },
    { id: 228, front: <h1>humiliate</h1>, back: <p>굴욕을 주다</p> },
    { id: 229, front: <h1>hunchback</h1>, back: <p>굽은 등, 허리가 구부러진 사람</p> },
    { id: 230, front: <h1>hypothesis</h1>, back: <p>가설, 가정</p> },
    { id: 231, front: <h1>ideal</h1>, back: <p>이상적인, 완벽한</p> },
    { id: 232, front: <h1>identical</h1>, back: <p>동일한, 똑같은</p> },
    { id: 233, front: <h1>identify</h1>, back: <p>식별하다, 알아보다</p> },
    { id: 234, front: <h1>illuminate</h1>, back: <p>밝게 하다, 명확히 하다</p> },
    { id: 235, front: <h1>immense</h1>, back: <p>거대한, 엄청난</p> },
    { id: 236, front: <h1>imminent</h1>, back: <p>임박한, 곧 일어날 것 같은</p> },
    { id: 237, front: <h1>impact</h1>, back: <p>영향, 충격</p> },
    { id: 238, front: <h1>implement</h1>, back: <p>실행하다, 도구</p> },
    { id: 239, front: <h1>improvise</h1>, back: <p>임기응변하다, 즉흥연주를 하다</p> },
    { id: 240, front: <h1>imprudent</h1>, back: <p>경솔한, 무모한</p> },
    { id: 241, front: <h1>incident</h1>, back: <p>사건, 사고</p> },
    { id: 242, front: <h1>incline</h1>, back: <p>기울다, 경사</p> },
    { id: 243, front: <h1>inclusive</h1>, back: <p>포괄적인, 포함하는</p> },
    { id: 244, front: <h1>induce</h1>, back: <p>유발하다, 유도하다</p> },
    { id: 245, front: <h1>infant</h1>, back: <p>유아, 갓난아이</p> },
    { id: 246, front: <h1>inflect</h1>, back: <p>(단어가) 어형변화를 하다</p> },
    { id: 247, front: <h1>inflict</h1>, back: <p>(괴로움을) 주다, 상처를 입히다</p> },
    { id: 248, front: <h1>infrastructure</h1>, back: <p>사회 기반 시설</p> },
    { id: 249, front: <h1>inhabit</h1>, back: <p>거주하다, 살다</p> },
    { id: 250, front: <h1>inhale</h1>, back: <p>들이마시다, 흡입하다</p> },
    { id: 251, front: <h1>inherit</h1>, back: <p>상속하다, 물려받다</p> },
    { id: 252, front: <h1>initial</h1>, back: <p>초기의, 처음의</p> },
    { id: 253, front: <h1>inquire</h1>, back: <p>조사하다, 물어보다</p> },
    { id: 254, front: <h1>inquisitive</h1>, back: <p>궁금한, 탐구심이 강한</p> },
    { id: 255, front: <h1>inscription</h1>, back: <p>문구, (적거나 새긴) 글</p> },
    { id: 256, front: <h1>insomnia</h1>, back: <p>불면증</p> },
    { id: 257, front: <h1>inspire</h1>, back: <p>영감을 주다, 고무하다</p> },
    { id: 258, front: <h1>institute</h1>, back: <p>연구기관, 설립하다</p> },
    { id: 259, front: <h1>instruct</h1>, back: <p>가르치다, 지시하다</p> },
    { id: 260, front: <h1>insulate</h1>, back: <p>단열하다, 방음처리하다</p> },
    { id: 261, front: <h1>insult</h1>, back: <p>모욕하다, 모욕</p> },
    { id: 262, front: <h1>intangible</h1>, back: <p>무형의, 손으로 만질 수 없는</p> },
    { id: 263, front: <h1>integrate</h1>, back: <p>통합하다, 통일하다</p> },
    { id: 264, front: <h1>intellect</h1>, back: <p>지성, 지능</p> },
    { id: 265, front: <h1>intelligent</h1>, back: <p>지적인, 영리한</p> },
    { id: 266, front: <h1>interaction</h1>, back: <p>상호 작용, 교감</p> },
    { id: 267, front: <h1>interfere</h1>, back: <p>간섭하다, 방해하다</p> },
    { id: 268, front: <h1>interpret</h1>, back: <p>해석하다, 통역하다</p> },
    { id: 269, front: <h1>interval</h1>, back: <p>간격, 기간</p> },
    { id: 270, front: <h1>intervene</h1>, back: <p>개입하다, 사이에 끼어들다</p> },
    { id: 271, front: <h1>intricate</h1>, back: <p>복잡한, 난해한</p> },
    { id: 272, front: <h1>invade</h1>, back: <p>침략하다, 침투하다</p> },
    { id: 273, front: <h1>irritate</h1>, back: <p>짜증나게 하다, 화나게 하다</p> },
    { id: 274, front: <h1>isolate</h1>, back: <p>고립시키다, 분리하다</p> },
    { id: 275, front: <h1>jeopardize</h1>, back: <p>위험에 빠뜨리다, 위태롭게 하다</p> },
    { id: 276, front: <h1>kidnap</h1>, back: <p>납치하다, 유괴하다</p> },
    { id: 277, front: <h1>lament</h1>, back: <p>한탄하다, 슬퍼하다</p> },
    { id: 278, front: <h1>lavish</h1>, back: <p>사치스러운, 아낌없는</p> },
    { id: 279, front: <h1>legitimate</h1>, back: <p>합법적인, 정당한</p> },
    { id: 280, front: <h1>lethal</h1>, back: <p>치명적인, 죽음을 초래하는</p> },
    { id: 281, front: <h1>likewise</h1>, back: <p>마찬가지로, 또한</p> },
    { id: 282, front: <h1>literature</h1>, back: <p>문학, 문헌</p> },
    { id: 283, front: <h1>lofty</h1>, back: <p>고상한, 높은</p> },
    { id: 284, front: <h1>longitude</h1>, back: <p>경도</p> },
    { id: 285, front: <h1>loyal</h1>, back: <p>충실한, 충직한</p> },
    { id: 286, front: <h1>malicious</h1>, back: <p>악의적인, 사악한</p> },
    { id: 287, front: <h1>maneuver</h1>, back: <p>작전, 조종하다</p> },
    { id: 288, front: <h1>manifest</h1>, back: <p>명시하다, 명백한</p> },
    { id: 289, front: <h1>manipulate</h1>, back: <p>조종하다, 조작하다</p> },
    { id: 290, front: <h1>marine</h1>, back: <p>해양의, 해군의</p> },
    { id: 291, front: <h1>mediate</h1>, back: <p>조정하다, 중재하다</p> },
    { id: 292, front: <h1>meditate</h1>, back: <p>사색하다, 명상하다</p> },
    { id: 293, front: <h1>merge</h1>, back: <p>합병하다, 융합하다</p> },
    { id: 294, front: <h1>metaphysical</h1>, back: <p>형이상학적인, 추상적인</p> },
    { id: 295, front: <h1>meteorology</h1>, back: <p>기상학</p> },
    { id: 296, front: <h1>mince</h1>, back: <p>(음식을) 잘게 썰다, 다지다</p> },
    { id: 297, front: <h1>minimum</h1>, back: <p>최소한의, 최소</p> },
    { id: 298, front: <h1>mischief</h1>, back: <p>장난, 나쁜 짓</p> },
    { id: 299, front: <h1>misplace</h1>, back: <p>잘못 놓다, 잃어버리다</p> },
    { id: 300, front: <h1>momentous</h1>, back: <p>중대한, 중요한</p> },
    { id: 301, front: <h1>moody</h1>, back: <p>기분 변화가 심한, 변덕스러운</p> },
    { id: 302, front: <h1>morale</h1>, back: <p>사기, 의욕</p> },
    { id: 303, front: <h1>motive</h1>, back: <p>동기, 이유</p> },
    { id: 304, front: <h1>muggy</h1>, back: <p>무더운, 습한</p> },
    { id: 305, front: <h1>murder</h1>, back: <p>살인하다, 살해하다</p> },
    { id: 306, front: <h1>nasty</h1>, back: <p>불쾌한, 나쁜</p> },
    { id: 307, front: <h1>neglect</h1>, back: <p>방치하다, 돌보지 않다</p> },
    { id: 308, front: <h1>neutral</h1>, back: <p>중립적인, 중간의</p> },
    { id: 309, front: <h1>notify</h1>, back: <p>통보하다, 알리다</p> },
    { id: 310, front: <h1>notorious</h1>, back: <p>악명 높은</p> },
    { id: 311, front: <h1>nuclear</h1>, back: <p>핵의, 원자력의</p> },
    { id: 312, front: <h1>numerous</h1>, back: <p>다수의, 많은</p> },
    { id: 313, front: <h1>nurture</h1>, back: <p>양육하다, 육성하다</p> },
    { id: 314, front: <h1>nutrition</h1>, back: <p>영양, 영양물</p> },
    { id: 315, front: <h1>obscure</h1>, back: <p>모호한, 무명의</p> },
    { id: 316, front: <h1>obstacle</h1>, back: <p>장애, 장애물</p> },
    { id: 317, front: <h1>obtain</h1>, back: <p>얻다, 획득하다</p> },
    { id: 318, front: <h1>occupy</h1>, back: <p>점유하다, 차지하다</p> },
    { id: 319, front: <h1>offend</h1>, back: <p>화나게 하다, 모욕하다</p> },
    { id: 320, front: <h1>offspring</h1>, back: <p>자손, 후예</p> },
    { id: 321, front: <h1>opposite</h1>, back: <p>반대의, 반대편의</p> },
    { id: 322, front: <h1>orthodox</h1>, back: <p>정통적인, 정통의</p> },
    { id: 323, front: <h1>outcome</h1>, back: <p>결과, 성과</p> },
    { id: 324, front: <h1>outline</h1>, back: <p>개요, 윤곽</p> },
    { id: 325, front: <h1>output</h1>, back: <p>산출물, 생산량</p> },
    { id: 326, front: <h1>outstanding</h1>, back: <p>뛰어난, 눈에 띄는</p> },
    { id: 327, front: <h1>panel</h1>, back: <p>(넓은) 판, 좌담회 참석자</p> },
    { id: 328, front: <h1>paradox</h1>, back: <p>역설, 모순</p> },
    { id: 329, front: <h1>passage</h1>, back: <p>통로, 통행</p> },
    { id: 330, front: <h1>pedagogy</h1>, back: <p>교육학, 교육법</p> },
    { id: 331, front: <h1>peninsula</h1>, back: <p>반도</p> },
    { id: 332, front: <h1>perspire</h1>, back: <p>땀을 흘리다, 발한하다</p> },
    { id: 333, front: <h1>persuade</h1>, back: <p>설득하다, 납득시키다</p> },
    { id: 334, front: <h1>pertinent</h1>, back: <p>적절한, 관련된</p> },
    { id: 335, front: <h1>pessimism</h1>, back: <p>비관주의, 염세주의</p> },
    { id: 336, front: <h1>philosophy</h1>, back: <p>철학</p> },
    { id: 337, front: <h1>physics</h1>, back: <p>물리학</p> },
    { id: 338, front: <h1>pious</h1>, back: <p>신실한, 독실한</p> },
    { id: 339, front: <h1>plain</h1>, back: <p>분명한, 평야</p> },
    { id: 340, front: <h1>poach</h1>, back: <p>밀렵하다, 가로채다</p> },
    { id: 341, front: <h1>poultry</h1>, back: <p>가금류</p> },
    { id: 342, front: <h1>precarious</h1>, back: <p>위태로운, 불안정한</p> },
    { id: 343, front: <h1>precede</h1>, back: <p>앞서다, 우선하다</p> },
    { id: 344, front: <h1>precipitation</h1>, back: <p>강수량, 강수</p> },
    { id: 345, front: <h1>predator</h1>, back: <p>포식자, 약탈자</p> },
    { id: 346, front: <h1>predict</h1>, back: <p>예측하다, 예견하다</p> },
    { id: 347, front: <h1>prejudice</h1>, back: <p>편견, 선입견</p> },
    { id: 348, front: <h1>premier</h1>, back: <p>주요한, 총리</p> },
    { id: 349, front: <h1>preserve</h1>, back: <p>보존하다, 보호하다</p> },
    { id: 350, front: <h1>priest</h1>, back: <p>사제, 신부</p> },
    { id: 351, front: <h1>primer</h1>, back: <p>입문서</p> },
    { id: 352, front: <h1>privilege</h1>, back: <p>특권, 특전</p> },
    { id: 353, front: <h1>procedure</h1>, back: <p>절차, 순서</p> },
    { id: 354, front: <h1>proceed</h1>, back: <p>진행하다, 계속하다</p> },
    { id: 355, front: <h1>prohibit</h1>, back: <p>금지하다, 방해하다</p> },
    { id: 356, front: <h1>promote</h1>, back: <p>촉진하다, 승진시키다</p> },
    { id: 357, front: <h1>prospect</h1>, back: <p>전망, 가능성</p> },
    { id: 358, front: <h1>prosper</h1>, back: <p>번영하다, 번창하다</p> },
    { id: 359, front: <h1>quantity</h1>, back: <p>양, 분량</p> },
    { id: 360, front: <h1>quench</h1>, back: <p>갈증을 해소하다, 불을 끄다</p> },
    { id: 361, front: <h1>queue</h1>, back: <p>줄, 줄을 서다</p> },
    { id: 362, front: <h1>random</h1>, back: <p>무작위의, 우연한</p> },
    { id: 363, front: <h1>recognize</h1>, back: <p>인식하다, 알아보다</p> },
    { id: 364, front: <h1>refine</h1>, back: <p>정제하다, 불순물을 제거하다</p> },
    { id: 365, front: <h1>reform</h1>, back: <p>개혁하다, 개정하다</p> },
    { id: 366, front: <h1>refund</h1>, back: <p>환불 금액, 환불하다</p> },
    { id: 367, front: <h1>register</h1>, back: <p>등록하다, 기록하다</p> },
    { id: 368, front: <h1>regulate</h1>, back: <p>규제하다, 조절하다</p> },
    { id: 369, front: <h1>reject</h1>, back: <p>거절하다, 거부하다</p> },
    { id: 370, front: <h1>rejoice</h1>, back: <p>매우 기뻐하다</p> },
    { id: 371, front: <h1>relevant</h1>, back: <p>관련 있는, 적절한</p> },
    { id: 372, front: <h1>relieve</h1>, back: <p>완화하다, 덜다</p> },
    { id: 373, front: <h1>remit</h1>, back: <p>송금하다, 사면하다</p> },
    { id: 374, front: <h1>represent</h1>, back: <p>대표하다, 나타내다</p> },
    { id: 375, front: <h1>reproach</h1>, back: <p>비난하다, 책망하다</p> },
    { id: 376, front: <h1>reside</h1>, back: <p>거주하다, 살다</p> },
    { id: 377, front: <h1>resign</h1>, back: <p>사퇴하다, 포기하다</p> },
    { id: 378, front: <h1>resister</h1>, back: <p>저항하는 사람, 반대자</p> },
    { id: 379, front: <h1>resolve</h1>, back: <p>해결하다, 결심하다</p> },
    { id: 380, front: <h1>respire</h1>, back: <p>호흡하다, 숨을 쉬다</p> },
    { id: 381, front: <h1>restore</h1>, back: <p>복구하다, 회복하다</p> },
    { id: 382, front: <h1>restrict</h1>, back: <p>제한하다, 한정하다</p> },
    { id: 383, front: <h1>resume</h1>, back: <p>재개하다, 다시 시작하다</p> },
    { id: 384, front: <h1>reveal</h1>, back: <p>드러내다, 밝히다</p> },
    { id: 385, front: <h1>revolution</h1>, back: <p>혁명, 회전</p> },
    { id: 386, front: <h1>revolve</h1>, back: <p>회전하다, 돌다</p> },
    { id: 387, front: <h1>reward</h1>, back: <p>보상, 보상하다</p> },
    { id: 388, front: <h1>rhetoric</h1>, back: <p>수사학, 수사법</p> },
    { id: 389, front: <h1>rigid</h1>, back: <p>엄격한, 단단한</p> },
    { id: 390, front: <h1>rural</h1>, back: <p>시골의, 농촌의</p> },
    { id: 391, front: <h1>sacrifice</h1>, back: <p>희생, 희생하다</p> },
    { id: 392, front: <h1>sanitation</h1>, back: <p>위생, 공중위생</p> },
    { id: 393, front: <h1>satellite</h1>, back: <p>인공위성, 위성</p> },
    { id: 394, front: <h1>saturate</h1>, back: <p>흠뻑 적시다, 포화상태로 만들다</p> },
    { id: 395, front: <h1>scarce</h1>, back: <p>부족한, 희귀한</p> },
    { id: 396, front: <h1>scatter</h1>, back: <p>흩뿌리다, 분산시키다</p> },
    { id: 397, front: <h1>scent</h1>, back: <p>향기, 냄새</p> },
    { id: 398, front: <h1>scholar</h1>, back: <p>학자, 지식인</p> },
    { id: 399, front: <h1>scorch</h1>, back: <p>그슬리다, 겉을 태우다</p> },
    { id: 400, front: <h1>scratch</h1>, back: <p>긁다, 긁히다</p> },
    { id: 401, front: <h1>segment</h1>, back: <p>부분, 조각</p> },
    { id: 402, front: <h1>segregate</h1>, back: <p>분리하다, 격리하다</p> },
    { id: 403, front: <h1>segregation</h1>, back: <p>인종 차별, 분리</p> },
    { id: 404, front: <h1>separate</h1>, back: <p>분리된, 별개의</p> },
    { id: 405, front: <h1>severe</h1>, back: <p>엄격한, 심한</p> },
    { id: 406, front: <h1>shabby</h1>, back: <p>낡은, 초라한</p> },
    { id: 407, front: <h1>share</h1>, back: <p>공유하다, 나누다</p> },
    { id: 408, front: <h1>shatter</h1>, back: <p>산산조각 나다, 부수다</p> },
    { id: 409, front: <h1>shelter</h1>, back: <p>피난처, 보호하다</p> },
    { id: 410, front: <h1>shiver</h1>, back: <p>떨리다, 전율</p> },
    { id: 411, front: <h1>shorthand</h1>, back: <p>속기, 속기법</p> },
    { id: 412, front: <h1>skull</h1>, back: <p>두개골</p> },
    { id: 413, front: <h1>skyscraper</h1>, back: <p>고층 건물, 마천루</p> },
    { id: 414, front: <h1>slaughter</h1>, back: <p>도살하다, 학살하다</p> },
    { id: 415, front: <h1>smuggle</h1>, back: <p>밀수하다</p> },
    { id: 416, front: <h1>snarl</h1>, back: <p>으르렁거리다, 고함치다</p> },
    { id: 417, front: <h1>sneak</h1>, back: <p>몰래 움직이다, 몰래 가져가다</p> },
    { id: 418, front: <h1>solicit</h1>, back: <p>간청하다, 구걸하다</p> },
    { id: 419, front: <h1>solstice</h1>, back: <p>최고점, 하지점</p> },
    { id: 420, front: <h1>spank</h1>, back: <p>(엉덩이를) 찰싹 때리다</p> },
    { id: 421, front: <h1>split</h1>, back: <p>나누다, 쪼개다</p> },
    { id: 422, front: <h1>spontaneous</h1>, back: <p>자발적인, 자연적인</p> },
    { id: 423, front: <h1>sprain</h1>, back: <p>손목, 발목을 삐다</p> },
    { id: 424, front: <h1>sprout</h1>, back: <p>싹트다, 새싹</p> },
    { id: 425, front: <h1>stagnant</h1>, back: <p>흐르지 않는, 정체된</p> },
    { id: 426, front: <h1>stammer</h1>, back: <p>말을 더듬다</p> },
    { id: 427, front: <h1>startle</h1>, back: <p>깜짝 놀라게 하다, 깜짝 놀라다</p> },
    { id: 428, front: <h1>status</h1>, back: <p>상태, 지위</p> },
    { id: 429, front: <h1>steep</h1>, back: <p>가파른, 급경사의</p> },
    { id: 430, front: <h1>stiff</h1>, back: <p>딱딱한, 경직된</p> },
    { id: 431, front: <h1>stoop</h1>, back: <p>몸을 굽히다, 웅크리다</p> },
    { id: 432, front: <h1>strain</h1>, back: <p>무리하게 사용하다, 긴장</p> },
    { id: 433, front: <h1>streak</h1>, back: <p>줄무늬, 선</p> },
    { id: 434, front: <h1>strict</h1>, back: <p>엄격한, 엄한</p> },
    { id: 435, front: <h1>strife</h1>, back: <p>갈등, 분쟁</p> },
    { id: 436, front: <h1>strip</h1>, back: <p>벗기다, 긴 조각</p> },
    { id: 437, front: <h1>stroll</h1>, back: <p>산책하다, 돌아다니다</p> },
    { id: 438, front: <h1>struggle</h1>, back: <p>노력하다, 사투</p> },
    { id: 439, front: <h1>submerge</h1>, back: <p>가라앉히다, 잠수하다</p> },
    { id: 440, front: <h1>substantial</h1>, back: <p>상당한, 튼튼한ㅁ</p> },
    { id: 441, front: <h1>substitute</h1>, back: <p>대체하다, 대용품</p> },
    { id: 442, front: <h1>sulky</h1>, back: <p>시무룩한, 억울해하는</p> },
    { id: 443, front: <h1>supervise</h1>, back: <p>감독하다, 관리하다</p> },
    { id: 444, front: <h1>supreme</h1>, back: <p>최고의, 최상의</p> },
    { id: 445, front: <h1>sustain</h1>, back: <p>지탱하다, 지속시키다</p> },
    { id: 446, front: <h1>swallow</h1>, back: <p>삼키다, 제비</p> },
    { id: 447, front: <h1>swarm</h1>, back: <p>무리, 떼 지어 다니다</p> },
    { id: 448, front: <h1>swift</h1>, back: <p>빠른, 신속한</p> },
    { id: 449, front: <h1>sympathy</h1>, back: <p>공감, 동정</p> },
    { id: 450, front: <h1>synonym</h1>, back: <p>동의어, 유의어</p> },
    { id: 451, front: <h1>synthesize</h1>, back: <p>합성하다, 종합하다</p> },
    { id: 452, front: <h1>tease</h1>, back: <p>놀리다, 괴롭히다</p> },
    { id: 453, front: <h1>temporary</h1>, back: <p>일시적인, 임시의</p> },
    { id: 454, front: <h1>tendency</h1>, back: <p>경향, 성향</p> },
    { id: 455, front: <h1>tentative</h1>, back: <p>임시적인, 불확실한</p> },
    { id: 456, front: <h1>territory</h1>, back: <p>영토, 영역</p> },
    { id: 457, front: <h1>testify</h1>, back: <p>증언하다, 입증하다</p> },
    { id: 458, front: <h1>theme</h1>, back: <p>주제, 테마</p> },
    { id: 459, front: <h1>thrive</h1>, back: <p>번창하다, 번성하다</p> },
    { id: 460, front: <h1>throb</h1>, back: <p>욱신거리다, 두근거리다</p> },
    { id: 461, front: <h1>throng</h1>, back: <p>무리, 군중</p> },
    { id: 462, front: <h1>thrust</h1>, back: <p>밀어넣다, 밀치다</p> },
    { id: 463, front: <h1>tissue</h1>, back: <p>조직, 종이</p> },
    { id: 464, front: <h1>torrent</h1>, back: <p>급류, 폭풍우</p> },
    { id: 465, front: <h1>toxic</h1>, back: <p>유독한, 독성의</p> },
    { id: 466, front: <h1>trace</h1>, back: <p>추적하다, 자취</p> },
    { id: 467, front: <h1>trait</h1>, back: <p>특성, 특징</p> },
    { id: 468, front: <h1>tranquil</h1>, back: <p>고요한, 평온한</p> },
    { id: 469, front: <h1>transition</h1>, back: <p>전환, 변이</p> },
    { id: 470, front: <h1>tread</h1>, back: <p>밟다, 걸음</p> },
    { id: 471, front: <h1>treaty</h1>, back: <p>조약, 협정</p> },
    { id: 472, front: <h1>tremble</h1>, back: <p>떨다, 전율하다</p> },
    { id: 473, front: <h1>trial</h1>, back: <p>시험, 재판</p> },
    { id: 474, front: <h1>tyrant</h1>, back: <p>폭군, 독재자</p> },
    { id: 475, front: <h1>ulcer</h1>, back: <p>궤양</p> },
    { id: 476, front: <h1>undergo</h1>, back: <p>겪다, 경험하다</p> },
    { id: 477, front: <h1>urban</h1>, back: <p>도시의</p> },
    { id: 478, front: <h1>urge</h1>, back: <p>재촉하다, 충동</p> },
    { id: 479, front: <h1>vague</h1>, back: <p>희미한, 모호한</p> },
    { id: 480, front: <h1>valid</h1>, back: <p>타당한, 유효한</p> },
    { id: 481, front: <h1>vanish</h1>, back: <p>사라지다, 없어지다</p> },
    { id: 482, front: <h1>ventilate</h1>, back: <p>환기하다, 바람이 통하게 하다</p> },
    { id: 483, front: <h1>verge</h1>, back: <p>길가, 경계</p> },
    { id: 484, front: <h1>verify</h1>, back: <p>확인하다, 입증하다</p> },
    { id: 485, front: <h1>versatile</h1>, back: <p>다방면의, 다재다능한</p> },
    { id: 486, front: <h1>vertical</h1>, back: <p>수직의, 세로의</p> },
    { id: 487, front: <h1>vexed</h1>, back: <p>골치 아픈, 짜증나는</p> },
    { id: 488, front: <h1>visible</h1>, back: <p>눈에 보이는, 명백한</p> },
    { id: 489, front: <h1>visual</h1>, back: <p>시각의, 시각적인</p> },
    { id: 490, front: <h1>vital</h1>, back: <p>생명의, 매우 중요한</p> },
    { id: 491, front: <h1>vulnerable</h1>, back: <p>취약한, 상처입기 쉬운</p> },
    { id: 492, front: <h1>waterproof</h1>, back: <p>방수의, 방수복</p> },
    { id: 493, front: <h1>welfare</h1>, back: <p>복지, 행복</p> },
    { id: 494, front: <h1>whereas</h1>, back: <p>~인 반면에</p> },
    { id: 495, front: <h1>withdraw</h1>, back: <p>인출하다, 철수하다</p> },
    { id: 496, front: <h1>worship</h1>, back: <p>숭배하다, 경배하다</p> },
    { id: 497, front: <h1>wreath</h1>, back: <p>화환, 화관</p> },
    { id: 498, front: <h1>wreck</h1>, back: <p>난파선, 파괴하다</p> },
    { id: 499, front: <h1>yield</h1>, back: <p>산출하다, 양보하다</p> },
    // More flashcards...
];

export default flashcards;
